info/__init__.py
from logging.handlers import RotatingFileHandler

from flask import Flask
import logging
# 用来指定Session保存的位置 (大写的)
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy

from redis import StrictRedis
from config import config
from flask_wtf import CSRFProtect
from flask_wtf.csrf import generate_csrf

# 初始化数据库
# 在Flask很多扩展里面都可以先初始化扩展 在去调用 init_app 方法初始化


db = SQLAlchemy()
redis_store = None  # type: StrictRedis


# 变量的注释  作用:方便在用的时候出现提示


def setup_log(config_name):
    # 设置日志的记录等级
    logging.basicConfig(level=config[config_name].LOG_LEVEL)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


def create_app(config_name):
    # 配置日志 传入配置名字 以便能够获取制定配置所对应的日志等级
    setup_log(config_name)
    # 创建Flask对象
    app = Flask(__name__)
    # 加载配置
    app.config.from_object(config[config_name])
    # 通过app初始化
    db.init_app(app)
    # 初始化redis 存储对象
    # 局部变量上升为全局变量
    global redis_store
    redis_store = StrictRedis(host=config[config_name].REDIS_HOST, port=config[config_name].REDIS_PORT,
                              decode_responses=True)
    # 开启当前项目 CSRF 保护 只做服务器验证
    CSRFProtect(app)

    # CSRFProtect 从cookie中取出随机值 从表单取出 对比 响应校验结果
    # 我们要做 1界面加载时 添加csrf_token 2表单中添加隐藏的csrf_token
    # 响应中统一设置cookie 请求钩子after_response
    # 通过ajax请求 不通过表单 通过herders请求头

    @app.after_request
    def after_request(response):
        # 生成一个随机的csrf_token
        csrf_token = generate_csrf()
        # 设置一个cookie
        response.set_cookie('csrf_token', csrf_token)

        return response

    # 设session保存指定位置
    Session(app)
    # 注册蓝图
    # 解决循环导入 在哪使用在哪导入
    from info.modules.index import index_blue
    app.register_blueprint(index_blue)

    from info.modules.passport import passport_blu
    app.register_blueprint(passport_blu)

    from info.modules.news import news_blu
    app.register_blueprint(news_blu)

    from info.modules.profile import profile_blu
    app.register_blueprint(profile_blu)
    # 自定义过滤器
    # 第一个参数是函数名，第二个参数是自定义的过滤器名称
    # 防止循环导入报错 db不能导
    from info.utils.common import do_index_class
    app.add_template_filter(do_index_class, 'index_class')

    from info.modules.admin import admin_blu
    app.register_blueprint(admin_blu)

    from info.utils.common import user_login_data
    from flask import render_template, g

    @app.errorhandler(404)
    @user_login_data
    def page_not_fount(e):
        # 传入data保持页面正常跳转 传入user保证登录功能
        user = g.user
        data = {"user": user.to_dict() if user else None}
        return render_template('news/404.html', data=data)

    return app

    # return app

info/modules/__init__.py
# 该模块是用于保存当前项目所有业务逻辑模块 eg:首页 新闻详情页 个人中心 后台管理

info/modules/admin/__init__.py
from flask import Blueprint, session, request, url_for, redirect

admin_blu = Blueprint('admin',__name__,url_prefix='/admin')
from . import views


# 只有admin函数 才调用
@admin_blu.before_request
def check_admin():
    is_admin = session.get('is_admin', False)
    # if 不是管理员 and 当前访问的url不是管理登录页:
    # 普通用户不能进入后台管理页面
    if not is_admin and not request.url.endswith(url_for('admin.login')):
        return redirect('/')

info/modules/admin/views.py
import time
from datetime import datetime, timedelta

from flask import render_template, request, jsonify, current_app, session, url_for, redirect, g, abort

from info import constants, db
from info.models import User, News, Category
from info.utils.common import user_login_data
from info.utils.image_storage import storage
from info.utils.response_code import RET
from . import admin_blu


# 用户登录 以及权限控制
@admin_blu.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        # 判断当前是否有登录，如果有登录直接重定向到管理员后台主页
        user_id = session.get('user_id', None)
        is_admin = session.get("is_admin", False)
        if user_id and is_admin:
            return redirect(url_for('admin.index'))

        return render_template('admin/login.html')

    # 取到登录的参数
    username = request.form.get('username')
    password = request.form.get('password')

    # 判断参数
    if not all([username, password]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误')

    try:
        user = User.query.filter(User.mobile == username, User.is_admin == True).first()
    except Exception as e:
        current_app.logger.error(e)
        # 不使用ajax 在当前界面 显示错误信息 不发生跳转
        return render_template('admin/login.html', errmsg='用户信息查询失败')

    if not user:
        return render_template('admin/login.html', errmsg='未查询到用户信息')

    if not user.check_passoword(password):
        return render_template('admin/login.html', errmsg='用户名或者密码错误')

    session['user_id'] = user.id
    session['mobile'] = user.mobile
    session["nick_name"] = user.nick_name
    session["is_admin"] = user.is_admin

    return redirect(url_for('admin.index'))


# 管理员首页
@admin_blu.route('/index')
@user_login_data
def index():
    user = g.user
    return render_template('admin/index.html', user=user.to_dict())


# 用户统计
@admin_blu.route('/user_count')
def user_count():
    # 统计总人数
    total_count = 0
    try:
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)

    # 获取当前时间
    t = time.localtime()
    # print(t)  time.struct_time(tm_year=2018, tm_mon=12, tm_mday=23,
    # tm_hour=11, tm_min=30, tm_sec=19, tm_wday=6, tm_yday=357,tm_isdst=0)

    # 月新增数
    # create_time > 本月1号
    mon_count = 0
    begin_mon_date_str = '%d-%02d-01' % (t.tm_year, t.tm_mon)
    # 字符串转换为时间对象
    begin_mon_date = datetime.strptime(begin_mon_date_str, "%Y-%m-%d")
    try:
        mon_count = User.query.filter(User.is_admin == False, User.create_time > begin_mon_date).count()
    except Exception as e:
        current_app.logger.error(e)

    # 日新增数
    # create_time > 今天日期
    day_count = 0
    begin_day_date_str = '%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday)
    begin_day_data = datetime.strptime(begin_day_date_str, "%Y-%m-%d")
    try:
        day_count = User.query.filter(User.is_admin == False, User.create_time > begin_day_data).count()
    except Exception as e:
        current_app.logger.error(e)

    # 拆线图数据
    active_time = []  # x轴
    active_count = []  # y轴
    # 取到今天的时间字符串
    today_date_str = '%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday)
    # 转成时间对象
    today_date = datetime.strptime(today_date_str, '%Y-%m-%d')

    for i in range(0, 31):  # 取不到31
        # 取到某一天的0点0分
        begin_date = today_date - timedelta(days=i)
        # timedelta代表两个datetime之间的时间差
        # 取到下一天的0点0分
        end_date = today_date - timedelta(days=(i - 1))
        count = User.query.filter(User.is_admin == False,
                                  User.last_login >= begin_date, User.last_login < end_date).count()
        # strftime 时间对象转换为字符串
        active_count.append(count)
        active_time.append(begin_date.strftime('%Y-%m-%d'))

    active_count.reverse()
    active_time.reverse()
    # print(active_time)
    # print(active_count)

    data = {
        'total_count': total_count,
        'mon_count': mon_count,
        'day_count': day_count,
        "active_time": active_time,
        "active_count": active_count

    }
    return render_template('admin/user_count.html', data=data)


# 用户列表显示
@admin_blu.route('/user_list')
def user_list():
    page = request.args.get('page', 1)

    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    users = []
    current_page = 1
    total_page = 1

    try:
        paginate = User.query.filter(User.is_admin == False).paginate(page, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
        users = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    user_dict_li = []
    for user in users:
        user_dict_li.append(user.to_admin_dict())

    data = {
        "users": user_dict_li,
        "total_page": total_page,
        "current_page": current_page,
    }

    return render_template('admin/user_list.html', data=data)


# 新闻审核功能  关键字搜索功能
@admin_blu.route('/news_review')
def news_review():
    page = request.args.get('page', 1)
    keywords = request.args.get('keywords', None)

    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    filters = [News.status != 0]
    # 如果关键字存在，那么就添加关键字搜索
    if keywords:
        # 关键字存在 查询标题中是否包含关键字
        filters.append(News.title.contains(keywords))
    news_list = []
    current_page = 1
    total_page = 1

    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()). \
            paginate(page, constants.USER_COLLECTION_MAX_NEWS, False)
        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_li = []
    for news in news_list:
        news_dict_li.append(news.to_review_dict())

    data = {
        'current_page': current_page,
        'total_page': total_page,
        'news_dict_li': news_dict_li
    }

    return render_template('admin/news_review.html', data=data)


# 审核详情
@admin_blu.route('/news_review_detail/<int:news_id>')
def news_review_detail(news_id):
    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)

    # print(news.to_dict())
    if not news:
        return render_template('admin/news_review_detail.html', data={'errmsg': '未查询到此新闻'})

    data = {"news": news.to_dict()}
    return render_template('admin/news_review_detail.html', data=data)


# 新闻内容审核
@admin_blu.route('/news_review_action', methods=['POST'])
def news_review_action():
    # 1. 接受参数
    news_id = request.json.get('news_id')
    action = request.json.get('action')

    # 2. 参数校验
    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误1')

    if action not in ('accept', 'reject'):
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误2')
    print(news_id)
    print(action)
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='数据查询失败')

    print(news)
    if not news:
        return jsonify(errno=RET.NODATA, errmsg='未查询到数据')

    # 代表接受
    if action == 'accept':
        news.status = 0

    # 代表拒绝
    else:
        reason = request.json.get('reason')

        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg='请输入拒绝原因')
        news.status = -1
        news.reason = reason

    return jsonify(errno=RET.OK, errmsg='OK')


# 新闻版式编辑
@admin_blu.route('/news_edit')
def news_edit():
    page = request.args.get('page', 1)
    keywords = request.args.get('keywords', None)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1

    filters = [News.status == 0]
    if keywords:
        filters.append(News.title.contains(keywords))
        print(keywords)
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()). \
            paginate(page, constants.USER_COLLECTION_MAX_NEWS, False)

        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    new_dict_li = []
    for news in news_list:
        new_dict_li.append(news.to_basic_dict())

    data = {
        'current_page': current_page,
        'total_page': total_page,
        'new_dict_li': new_dict_li
    }
    return render_template('admin/news_edit.html', data=data)


# 新闻编辑详情页 新闻编辑提交
@admin_blu.route('/news_edit_detail' , methods = ['POST','GET'])
def news_edit_detail():
    if request.method == 'GET':
        news_id = request.args.get('news_id')

        if not news_id:
            abort(404)

        try:
            news_id = int(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg='参数错误')

        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg='查询数据错误')

        if not news:
            return render_template('admin/news_edit_detail.html', errmsg='没有查询到数据1')

        # 查询分类数据
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            return render_template('admin/news_edit_detail.html', errmsg='没有查询到数据2')

        category_dict_li = []
        for category in categories:
            # 取到分类的字典
            cate_dict = category.to_dict()
            # 判断当前遍历到的分类是否是当前新闻的分类，如果是，则添加is_selected为true
            if category.id == news.category_id:
                cate_dict["is_selected"] = True
            category_dict_li.append(cate_dict)

        # 移除最新的分类
        category_dict_li.pop(0)

info/modules/index/__init__.py
from flask import Blueprint

# 创建蓝图对象
index_blue = Blueprint('index', __name__)

from . import views

info/modules/index/views.py
from flask import render_template, request, jsonify, g

from info import constants
from info.models import News, Category
from info.utils.common import user_login_data
from info.utils.response_code import RET
from . import index_blue
from flask import current_app


@index_blue.route('/')
@user_login_data
def index():
    """
     显示首页
    1. 如果用户已经登录，将当前登录用户的数据传到模板中，供模板显示
    :return:
    """
    # 取到用户id
    # user_id = session.get('user_id', None)
    # user = None  # type:User
    # if user_id:
    #     # 查询用户
    #     try:
    #         user = User.query.get(user_id)  # 得到一个对象 不能展示在浏览器
    #
    #     except Exception as e:
    #         current_app.logger.error(e)
    user = g.user
    # g 保存值用于函数的传递
    # 右侧新闻点击排行处理
    # 定义一个空的字典列表，里面装的就是字典
    new_list = []
    try:
        new_list = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)

    news_dict_li = []
    # 遍历对象列表，将对象的字典添加到字典列表中
    # [{new1},{new2},{new3}...]
    for news in new_list:
        news_dict_li.append(news.to_basic_dict())

    # if user:
    # print(user.to_dict())

    # 新闻分类展示
    # 查询分类数据,通过模板形式渲染
    categories = Category.query.all()
    category_li = []
    for category in categories:
        category_li.append(category.to_dict())

    # 三元表达式 有值 dict 没有 none
    # 从对象中获取数据 modules.py中 把字典返回给'user'

    data = {
        "user": user.to_dict() if user else None,
        'news_dict_li': news_dict_li,
        'category_li': category_li
    }

    return render_template('news/index.html', data=data)


@index_blue.route('/news_list')
def news_list():
    """
    获取首页新闻内容
    :return:
    """
    # 1.获取参数
    # 新闻的分类id
    cid = request.args.get('cid', '1')
    page = request.args.get('page', '1')
    per_page = request.args.get('per_page', '10')

    # 2. 验证参数
    try:
        cid = int(cid)
        page = int(page)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误')

    # 普通写法 ==>
    # try:
    #     if cid ==1:
    #         paginate = News.query.[filter()].
    #         order_by(News.create_time.desc()).paginate(page, per_page, False)
    #     else:
    #         paginate = News.query.filter(News.category_id == cid).
    #         order_by(News.create_time.desc()).paginate(page, per_page, False)
    # except Exception as e:
    #     current_app.logger.error(e)
    #     return jsonify(errno=RET.DBERR, errmsg='数据查询错误')

    # 条件拼接 不等于1 时 拼接  提取共同部分
    #  1)定义一个列表存放查询条件
    filters = [News.status == 0]
    #  查询的不是(最新)的数据
    #  2)对参数做判断，符合条件，将查询条件加入空列表
    if cid != 1:
        # 需要添加条件
        # 获得对象列表
        filters.append(News.category_id == cid)   # 查询条件 需要解包传入数据库查询条件

    try:
        #  3)查询时对列表里面内容进行解包
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='数据查询错误')

        # 取到当前页的数据
        # paginate返回一个Paginate对象

    news_model_list = paginate.items  # 模型对象列表 当前页数据 列表对象[news1,news2,news3...]
    # print(news_model_list)
    total_page = paginate.pages  # 总页数
    current_page = paginate.page  # 当前页

    news_dict_li = []
    for news in news_model_list:
        news_dict_li.append(news.to_basic_dict())

    data = {
        'total_page': total_page,
        'current_page': current_page,
        'news_dict_li': news_dict_li
    }
    return jsonify(errno=RET.OK, errmsg='OK', data=data)


@index_blue.route('/favicon.ico')
def favicon():
    return current_app.send_static_file('news/favicon.ico')

info/modules/news/__init__.py
from flask import Blueprint

news_blu = Blueprint('news', __name__, url_prefix='/news')

from . import views

info/modules/passport/__init__.py
from flask import Blueprint
passport_blu = Blueprint('passport', __name__, url_prefix='/passport')
from . import views

info/modules/profile/__init__.py
from flask import Blueprint
profile_blu = Blueprint('profile', __name__, url_prefix='/user')
from . import views

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    {% block cssBlock %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}

    {% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="{{ url_for("index.index") }}" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>

            {% block categoryBlock %}
                <ul class="menu fl">
                {% for category in data.category_li %}
{#                    active 表示选中#}
                    {% if loop.index==1 %}
                        <li class="active" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                    {% else %}
                        <li data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
             {% endblock %}
            {% if data.user %}

            <!-- 用户登录后显示下面，隐藏上面 -->
            <div class="user_login fr">
                <img src="{% if data.user.avatar_url %}
                {{ data.user.avatar_url }}{% else %}../../static/news/images/person01.png
                {% endif %}" class="lgin_pic">
                <a href="/user/info" id = 'nick_name'>{{ data.user.nick_name }}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
                    {#  点击之后不跳转 交给js进行处理  #}
            </div>
            {% else %}
                <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="conter_con">
        {% block contentBlock %}

        {% endblock %}
      {% block rankBlock %}
        <div class="rank_con fr">
        {% block authorBlock %}

        {% endblock %}



            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">

                {% for news in data.news_dict_li %}
{#                    当前循环迭代的次数（从 1 开始）#}
{#                    自定义过滤器的形式对 span 标签的 class 指定#}

                    <li><span class="{{loop.index | index_class}}">{{ loop.index }}</span><a href="/news/{{ news.id }}">{{ news.title }}</a></li>
                {% endfor %}

            </ul>
        </div>
       {% endblock %}
    </div>

{% block bottomBlock %}
    <div class="footer">
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>
{% endblock %}


    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/news/index.html
{% extends 'news/base.html' %}

{% block titleBlock %}
首页-新经资讯
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}


{% block contentBlock %}
<ul class="list_con fl">

</ul>
{% endblock %}

info/templates/news/user.html
{% extends "news/base.html" %}


{% block titleBlock %}
用户中心
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock %}

{% block contentBlock %}
<div class="user_menu_con fl">
    <div class="user_center_pic">
        <img src={% if data.user.avatar_url %}
            {{ data.user.avatar_url }}
        {% else %}
            "../../static/news/images/user_pic.png"
        {% endif %} alt="用户图片">
    </div>
    <div class="user_center_name">{{ data.user.nick_name }}</div>

    <ul class="option_list">
        <li class="active"><a href="{{ url_for('profile.user_base_info') }}" target="main_frame">基本资料</a></li>
        <li><a href="{{ url_for('profile.pic_info') }}" target="main_frame">头像设置</a></li>
        <li><a href="{{ url_for('profile.user_follow') }}" target="main_frame">我的关注</a></li>
        <li><a href="{{ url_for('profile.pass_info') }}" target="main_frame">密码修改</a></li>
        <li><a href="{{ url_for('profile.user_collection') }}" target="main_frame">我的收藏</a></li>
        <li><a href="{{ url_for('profile.news_release') }}" target="main_frame">新闻发布</a></li>
        <li><a href="{{ url_for('profile.user_news_list') }}" target="main_frame">新闻列表</a></li>
    </ul>
</div>

<div class="user_con fr">
    <iframe src="{{ url_for('profile.user_base_info') }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>

</div>
{% endblock %}

{% block rankBlock %}
{#重写rankBlock，内部什么什么都不填#}
{% endblock %}

info/templates/news/user_base_info.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
     <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
     <script type="text/javascript" src="../../static/news/js/user_base_info.js"></script>
</head>
<body class="inframe_body">
<form class="base_info">
    <h3>基本资料</h3>
    <div class="form-group">
        <label>个性签名：</label>
        <input type="text" id="signature" name="signature" class="input_txt" value="{{ data.user.signature }}">
    </div>
    <div class="form-group">
        <label>用户昵称：</label>
        <input type="text" id="nick_name" name="nick_name" class="input_txt" value="{{ data.user.nick_name }}">
    </div>
    <div class="form-group">
        <label>性别：</label>
        {% if data.user.gender == "MAN" %}
            <input class="gender" type="radio" name="gender" checked="checked" value="MAN"> <b>男</b>
            <input class="gender"  type="radio" name="gender" value="WOMAN">  <b>女</b>
        {% else %}
            <input class="gender" type="radio" name="gender" value="MAN"> <b>男</b>&nbsp;&nbsp;&nbsp;
            <input class="gender" type="radio" name="gender" value="WOMAN" checked="checked">  <b>女</b>
        {% endif %}
    </div>
    <div class="form-group">
        <input type="submit" value="保 存" class="input_sub">
    </div>
</form>
</body>
</html>